import type { Metadata } from "next";
import { Rubik } from 'next/font/google'
import "./globals.css";

const rubik = Rubik({
  subsets: [
    "latin"
  ],
  weight: '400'
})

export const metadata: Metadata = {
  title: "Pokédex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`background sm:p-2 p-1 ${rubik.className}`}
      >
        {children}
      </body>
    </html>
  );
}
